services:
  benchmark-mysql:
    image: mysql:8.0
    container_name: benchmark-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "33306:3306"
    volumes:
      - benchmark_db_data:/var/lib/mysql
      - ./db/benchmark/init.sql:/docker-entrypoint-initdb.d/init.sql

  benchmark-mysql-exporter:
    image: prom/mysqld-exporter
    container_name: benchmark-db-exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "test_user:test_password@(benchmark-mysql:3306)/test_db"
    command:
      - "--mysqld.username=test_user:test_password"
      - "--mysqld.address=benchmark-mysql:3306"
    depends_on:
      - benchmark-mysql
    ports:
      - "39104:9104"

  benchmark-prometheus:
    image: prom/prometheus:latest
    container_name: benchmark-prometheus
    restart: always
    volumes:
      - ./monitor/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "39090:9090"

  benchmark-grafana:
    image: grafana/grafana:latest
    container_name: benchmark-grafana
    restart: always
    ports:
      - "33000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  benchmark_db_data:
